Layout/LineLength:
  Max: 120

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile
    - Gemfile.lock

# TODO
Metrics/AbcSize:
  Enabled: false

# TODO
Layout/ArgumentAlignment:
  Enabled: false

# Allow:
#  expect {
#    any-
#    thing
#  }.to be_ok
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
    - 'spec/**/shared_examples/*.rb'

# Allow .to change {} dsl
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
    - 'spec/**/shared_examples/*.rb'

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Lint/BooleanSymbol:
  Enabled: false

Style/DoubleNegation:
  Enabled: false # TODO

Metrics/MethodLength:
  Max: 20

AllCops:
  Exclude:
    - 'spec/support/**/brew_formulae/**/*'
    - 'spec/support/bin/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/support/lib/viml_value/parser.rb'
    - 'spec/support/lib/viml_value/lexer.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'spec/support/vimrunner_neovim/**/*'
    - 'spec/support/dsl/**/*'

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

### Parser specs
# use %q|| instead of %q() to simplify escaping testing
Style/PercentQLiterals:
  Exclude:
    - 'spec/lib/viml_value/*_spec.rb'
    - 'spec/lib/viml_value_spec.rb'
Style/RedundantPercentQ: # to preserve alignments
  Exclude:
    - 'spec/lib/viml_value/*_spec.rb'
    - 'spec/lib/viml_value_spec.rb'
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%q':    '||'
    '%Q':    '||'
  Include:
    - 'spec/lib/viml_value/*_spec.rb'
    - 'spec/lib/viml_value_spec.rb'
