sudo: required

# https://docs.travis-ci.com/user/reference/linux/#overview
dist: xenial
# https://docs.travis-ci.com/user/reference/osx/#macos-version
osx_image: xcode9

# NOTE: Services are not supported on osx
services:
  - xvfb
env: DISPLAY=":99.0"

# https://docs.travis-ci.com/user/reference/osx/#ruby-versionsimplementations
# https://docs.travis-ci.com/user/reference/xenial/#ruby-support
rvm: 2.2.5
language: ruby

cache:
  bundler: true
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/.dep
    - $HOME/.rvm
    - $HOME/Library/Caches/Homebrew
before_cache:
  - which brew && brew cleanup # https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci

install:
  - |
    sh .ci/install_vim_dependencies.sh
    bundle install

    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      sh .ci/install_osx.sh
      mvim --version
    else
      sh .ci/install_linux.sh
      vim --version
    fi
    ack --version
    ag --version
    git --version
    grep --version
    pt --version
    rg --version

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then (( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok) &); sleep 5; fi
  # - if [ "$TRAVIS_OS_NAME" = "linux" ]; then DISPLAY=":99.0" sh -e /etc/init.d/xvfb start; sleep 5 fi 

after_failure:
  - env
  - ls -lah /usr/local/bin

jobs:
  include:
    - name: 'Test acceptance of #backend#system'
      script: bundle exec rspec --tag system
      os: osx
    - name: 'Test acceptance of #backend#vim8'
      script: bundle exec rspec --tag vim8
      os: osx
    - name: 'Test acceptance of #backend#vimproc'
      script: bundle exec rspec --tag vimproc
      os: osx

    - name: 'Test acceptance of #backend#system'
      script: bundle exec rspec --tag system
      os: linux
    - name: 'Test acceptance of #backend#vim8'
      script: bundle exec rspec --tag vim8
      os: linux
    - name: 'Test acceptance of #backend#vimproc'
      script: bundle exec rspec --tag vimproc
      os: linux

    - name: 'Unit tests'
      script: bundle exec rspec --tag ~backend
      os: linux
