sudo: required
dist: focal
env:
  DISPLAY=":99.0"
  PARALLEL_SPLIT_TEST_PROCESSES=2
services:
  - xvfb
rvm: 2.7.0
language: ruby
cache:
  bundler: true
  apt: true
  pip: true
  directories:
    - $HOME/.rvm
    - $HOME/.cache/pip
before_install:
  - |
    yes | gem update --system --force
    gem install bundler
install:
  - |
    sudo apt-get update
    sudo apt-get -y install ansible ruby-dev
    make provision-host build-serializer DOCKER_RUN=
before_script:
  - |
    vim --version || true
    ack --help || true
    ag --help || true
    grep --help || true
    rg --help || true
    pt --help || true
    git grep -h || true
jobs:
  include:
    - name: 'Unit tests'
      script: |
        vim -Nu <(cat << VIMRC
        set rtp+=~/.cache/esearch-dev/plugins/vader.vim
        set rtp+=.
        VIMRC) -c 'Vader! spec/*.vader' > /dev/null
        bundle exec parallel_test -n 2 --type rspec spec/unit/
      os: linux
    - name: 'Acceptance tests of #backend#system patterns'
      script: bundle exec parallel_split_test spec/plugin/backend/patterns_spec.rb --tag system --tag ~render:viml
      os: linux
    - name: 'Acceptance tests of #backend#system paths'
      script: bundle exec parallel_split_test spec/plugin/backend/paths_spec.rb --tag system	--tag ~render:viml
      os: linux
    - name: 'Acceptance tests of #backend#vim8 patterns'
      script: bundle exec parallel_split_test spec/plugin/backend/patterns_spec.rb --tag vim8
      os: linux
    - name: 'Acceptance tests of #backend#vim8 paths with #viml legacy render'
      script: bundle exec parallel_split_test spec/plugin/backend/paths_spec.rb --tag vim8 --tag ~render:lua
      os: linux
    - name: 'Acceptance tests of #backend#vim8 paths with #lua render'
      script: bundle exec parallel_split_test spec/plugin/backend/paths_spec.rb --tag vim8 --tag ~render:viml
      os: linux
    - name: 'Acceptance tests adapter and modifiable features'
      script: bundle exec rspec --tag adapters
      os: linux
    - name: 'Acceptance tests of commandline'
      script: bundle exec parallel_test -n 2 --type rspec spec/plugin/commandline/
      os: linux
    - name: 'Linters (luacheck, rubocop, vint, shellcheck)'
      script:
        - luacheck lua/
        - "vint autoload/esearch/ autoload/esearch.vim plugin syntax"
        - bundle exec rubocop --display-cop-names
      os: linux
