sudo: required
dist: xenial
osx_image: xcode11.2	

services:
  - xvfb

env: DISPLAY=":99.0"

# https://docs.travis-ci.com/user/reference/osx/#ruby-versionsimplementations
# https://docs.travis-ci.com/user/reference/xenial/#ruby-support
rvm: 2.4.3
language: ruby

cache:
  bundler: true
  directories:
    - $HOME/.rvm

jobs:
  include:
    - script: bash .ci/before_script.sh && rake ci_system
      name: 'Test #backend#system'
      os: osx
      # env: ESEARCH_BACKEND=system
    - script: bash .ci/before_script.sh && rake ci_vim8
      name: 'Test #backend#vim8'
      os: osx
      # env: ESEARCH_BACKEND=vim8
    - script: bash .ci/before_script.sh && rake ci_vimproc
      name: 'Test #backend#vimproc'
      os: osx
      # env: ESEARCH_BACKEND=vimproc
      #
      #
    - script: bash .ci/before_script.sh && rake ci_system
      name: 'Test #backend#system'
      os: linux
      # dist: xenial
      # env: ESEARCH_BACKEND=system
    - script: bash .ci/before_script.sh && rake ci_vim8
      name: 'Test #backend#vim8'
      os: linux
      # dist: xenial
      # env: ESEARCH_BACKEND=vim8
    - script: bash .ci/before_script.sh && rake ci_vimproc
      name: 'Test #backend#vimproc'
      os: linux
      # dist: xenial
      # env: ESEARCH_BACKEND=vimproc
