sudo: required

# https://docs.travis-ci.com/user/reference/linux/#overview
dist: xenial
# https://docs.travis-ci.com/user/reference/osx/#macos-version
osx_image: xcode9.2

# NOTE: Services are not supported on osx
services:
  - xvfb
env: DISPLAY=":99.0"

# https://docs.travis-ci.com/user/reference/osx/#ruby-versionsimplementations
# https://docs.travis-ci.com/user/reference/xenial/#ruby-support
rvm: 2.2.5
language: ruby

cache:
  bundler: true
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/.dep
    - $HOME/.rvm
    - $HOME/Library/Caches/Homebrew
before_cache:
  - which brew && brew cleanup # https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci

jobs:
  include:
    - name: 'Test acceptance of #backend#system'
      script: travis_wait 60 bash .ci/before_script.sh && bundle exec rspec --tag system
      os: osx
    - name: 'Test acceptance of #backend#vim8'
      script: travis_wait 60 bash .ci/before_script.sh && bundle exec rspec --tag vim8
      os: osx
    - name: 'Test acceptance of #backend#vimproc'
      script: travis_wait 60 bash .ci/before_script.sh && bundle exec rspec --tag vimproc
      os: osx

    - name: 'Test acceptance of #backend#system'
      script: bash .ci/before_script.sh && bundle exec rspec --tag system
      os: linux
    - name: 'Test acceptance of #backend#vim8'
      script: bash .ci/before_script.sh && bundle exec rspec --tag vim8
      os: linux
    - name: 'Test acceptance of #backend#vimproc'
      script: bash .ci/before_script.sh && bundle exec rspec --tag vimproc
      os: linux

    - name: 'Unit tests'
      script: bash .ci/before_script.sh && bundle exec rspec --tag ~backend
      os: linux
