sudo: required
dist: xenial
osx_image: xcode9.2	# https://docs.travis-ci.com/user/reference/osx/

services:
  - xvfb

env: DISPLAY=":99.0"

# https://docs.travis-ci.com/user/reference/osx/#ruby-versionsimplementations
# https://docs.travis-ci.com/user/reference/xenial/#ruby-support
rvm: 2.2.5
# Workaround: https://github.com/travis-ci/travis-ci/issues/5361
before_install:
  - rvm get stable --auto-dotfiles
  - rvm install 2.2.5
language: ruby

cache:
  bundler: true
  directories:
    - $HOME/.rvm

jobs:
  include:
    - script: bash .ci/before_script.sh && rake ci_system
      name: 'Test #backend#system'
      os: osx
    - script: bash .ci/before_script.sh && rake ci_vim8
      name: 'Test #backend#vim8'
      os: osx
    - script: bash .ci/before_script.sh && rake ci_vimproc
      name: 'Test #backend#vimproc'
      os: osx

    - script: bash .ci/before_script.sh && rake ci_system
      name: 'Test #backend#system'
      os: linux
    - script: bash .ci/before_script.sh && rake ci_vim8
      name: 'Test #backend#vim8'
      os: linux
    - script: bash .ci/before_script.sh && rake ci_vimproc
      name: 'Test #backend#vimproc'
      os: linux
