sudo: required

# https://docs.travis-ci.com/user/reference/linux/#overview
dist: xenial
# https://docs.travis-ci.com/user/reference/osx/#macos-version
osx_image: xcode9.2

# NOTE: Services are not supported on osx
services:
  - xvfb
env: DISPLAY=":99.0"

# https://docs.travis-ci.com/user/reference/osx/#ruby-versionsimplementations
# https://docs.travis-ci.com/user/reference/xenial/#ruby-support
rvm: 2.2.5
language: ruby

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/.dep
    - $HOME/.rvm
    - $HOME/Library/Caches/Homebrew
before_cache:
  - which brew && brew cleanup # https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci

jobs:
  include:
    - script: travis_wait 30 bash .ci/before_script.sh && rspec --tag system
      name: 'Test #backend#system'
      os: osx
    - script: travis_wait 30 bash .ci/before_script.sh && rspec --tag vim8
      name: 'Test #backend#vim8'
      os: osx
    - script: travis_wait 30 bash .ci/before_script.sh && rspec --tag vimproc
      name: 'Test #backend#vimproc'
      os: osx

    - script: bash .ci/before_script.sh && rspec --tag system
      name: 'Test #backend#system'
      os: linux
    - script: bash .ci/before_script.sh && rspec --tag vim8
      name: 'Test #backend#vim8'
      os: linux
    - script: bash .ci/before_script.sh && rspec --tag vimproc
      name: 'Test #backend#vimproc'
      os: linux
