- hosts: localhost
  gather_facts: yes
  connection: local
  tasks:
    - include_vars: "{{ ansible_os_family | lower }}.yml"

    - name: Setup global dependencies
      block:
        - name: Packages
          package:
            name: "{{ item }}"
            state: present
          become: "{{ package_become }}"
          with_items:
            - luarocks
            - git
            - curl
            - ragel
            - unzip
            - neovim
            - "{{ vim_package_name }}"
            - "{{ tar_package_name }}"
            - "{{ pip_package_name }}"
            - "{{ ps_package_name }}"
        - name: Lua linter
          command: luarocks install luacheck
          become: "{{ package_become }}"
          args:
            creates: /usr/local/bin/luacheck
        - name: Vim lint
          pip:
            name: ['vim-vint']
            state: present

    - name: Setup greppers
      block:
        - name: From system package manager
          package:
            name: '{{ item }}'
            state: present
          become: "{{ package_become }}"
          with_items:
            - "{{ ag_package_name }}"
            - "{{ ack_package_name }}"
        - name: From PIP
          pip:
            name: ['semgrep']
            state: present

        - name: Install prebuilt
          block:
            - name: Download
              unarchive:
                src: "{{ item.download_url }}"
                dest: /tmp
                remote_src: yes
              with_items: "{{ greppers }}"
            - name: Find
              find:
                paths: /tmp
                recurse: yes
                patterns: '{{ item.bin }}'
              register: bins
              with_items: '{{ greppers }}'
            - name: Copy into /usr/local/bin
              copy:
                src: '{{ item.path }}'
                dest: '/usr/local/bin/{{ item.path | basename }}'
              become: "{{ package_become }}"
              with_items: '{{ bins.results | map(attribute="files") | map("first") | list }}'
            - name: Make executable
              file:
                dest: '/usr/local/bin/{{ item.bin }}'
                mode: a+x
              with_items: '{{ greppers }}'
          vars:
            - greppers:
              - {bin: pt, download_url: "{{ pt_download_url }}"}
              - {bin: rg, download_url: "{{ rg_download_url }}"}
        - name: Configure git-grep
          block:
            - git_config: {scope: global, name: core.precomposeunicode, value: 'true'}
            - git_config: {scope: global, name: core.quotePath, value: 'false'}

    - name: Setup plugin dependencies
      git:
        repo: https://github.com/mg979/vim-visual-multi.git
        dest: ~/.cache/esearch-dev/plugins/vim-visual-multi

    - name: Setup testing dependencies
      block:
        - name: Install libs
          bundler:
            state: present
        - name: Setup vader testing framework
          git:
            repo: https://github.com/junegunn/vader.vim.git
            dest: ~/.cache/esearch-dev/plugins/vader.vim
